name: optisignbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/optisignbot
  build_command: pip install -r requirements.txt
  run_command: python main.py
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${OPENAI_API_KEY}

jobs:
- name: scrape-articles
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/optisignbot
  schedule: "0 0 * * *"  # Run once daily at midnight
  run_command: python cron_scrape.py
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${OPENAI_API_KEY} 