name: optisign-bot
services: []
workers:
- name: optisign-daily-worker
  source_dir: /
  github:
    repo: dennis-nguyen0909/Optisigns
    branch: main
  run_command: python daily_job.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: TZ
    scope: RUN_TIME
    type: GENERAL
    value: Asia/Ho_Chi_Minh
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED 