name: optisign-bot
services: []
workers:
- name: optisign-daily-worker
  source_dir: /
  github:
    repo: your-username/your-repo-name  # Update this with your actual GitHub repo
    branch: main
  run_command: python daily_job.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: your-openai-api-key-here  # You'll set this in DO dashboard
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED 